[pytest]
testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -v --html=reports/report.html --self-contained-html --strict-markers

markers =
    smoke: Critical smoke tests
    regression: Regression test suite
    negative: Negative test scenarios
    ui: UI automation tests
